### ISSUE TITLE
Run local tests should be learn submit

### ISSUE THREAD

**Issue by Hector-Ariceaga** [learn-co-curriculum/js-basics-control-flow-lab#13]
README instructs student to `Run Local Tests` at the end of the lab. This returns an error. `Learn Submit` submits the assignment.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
