### ISSUE TITLE
Share success on Facebook not working

### ISSUE THREAD

**Issue by sjwakeman** [learn-co-curriculum/js-basics-control-flow-lab#15]
Click on Share button with Facebook highlighted.
SHARE YOUR SUCCESS, TELL THE WORLD!
FULL STACK WEB DEVELOPMENT V6
I solved "Control Flow Lab"
TOTAL LESSONS
461
COMPLETED
User avatar
Scott Wakeman
learn.co/sjwakeman
Add a message
SELECT ONE OR BOTH TO SHARE

Something went wrong. Please retry

A pop up window launches when click on the Facebook icon when attempting to submit a second time:

500
Something went wrong
We're sorry - an internal server error occurred.

Windows 10 
Running Oracle VM VirtualBox Manager 
Version 5.2.26 r128414 (Qt5.6.2)
Chromium web browser

I get the identical issue when using Google Chrome on my Windows 10 computer NOT using Oracle VM VirtualBox Manager.

This has been occurring since April 4 so I decided to create an issue since it has been over a week with no resolution.

Thanks for your attention to this matter,

Scott Wakeman

**Comment by lizbur10** [comment]
Hey Scott! Sorry this is been sitting here so long :) I'm assuming the problem has been fixed by now so I'm going to close this issue.

Thanks for contributing to the Flatiron curriculum! 💙
