### ISSUE TITLE
readme / test slight difference

### ISSUE THREAD

**Issue by sdklos** [learn-co-curriculum/js-basics-control-flow-lab#3]
this is the first test in the readme:

`describe('index.js', () => {
  describe('first 400 feet are free', () => {
    it('gives customers a free sample', () => {
      expect(scuberGreetingForFeet(199)).to.equal("This one is on me!");
    })
    // tests continue...
  })
})`

this is the first test in the test file:

`describe('index.js', function () {
  describe('scuberGreetingForFeet()', function () {
    it('gives customers a free sample', function () {
      expect(scuberGreetingForFeet(199)).to.equal('This one is on me!');
    });
`

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/js-basics-control-flow-lab/commit/3ec9051ef1e0ad63069a60b67bb041575d623d2c. Thanks @sdklos !
