### ISSUE TITLE
Requiring functions prior to functions lesson

### ISSUE THREAD

**Issue by ThePeej** [learn-co-curriculum/js-basics-control-flow-lab#5]
Hello there!

I was going through this lab, and I was not sure if we needed to define and use functions. That is the impression I got looking over the index-test.js file and the test error feedback. If that is the case, it seems a bit confusing since I was assuming functions were not to be used much prior to the actual function lessons

May or may not be an issue, but I figured I'd send the feedback in case it was! :)

-PJ

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ThePeej.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
