### ISSUE TITLE
functions readme should be here

### ISSUE THREAD

**Issue by ddhogan** [learn-co-curriculum/js-basics-control-flow-lab#6]
Hi-
This lab asks the user to write functions, which haven't been mentioned yet in the lessons.  Perhaps this lab could ask the user to write code blocks instead, or rearrange the lessons so the functions stuff comes before this?

Thanks!

**Comment by ddhogan** [comment]
Just noticed this has been raised before.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ddhogan.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
