### ISSUE TITLE
Pedagogical issue: why have the lab comprise functions for conditionals when the curriculum has not gone over that yet?

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/js-basics-control-flow-lab#7]
Javascript functions are explained *after* this lab in the curriculum. I am unclear how this is optimal for learning.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @justinddaniel.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
