### ISSUE TITLE
Confusing placement in curriculum

### ISSUE THREAD

**Issue by mbalsamo2** [learn-co-curriculum/js-basics-control-flow-lab#8]
This lab comes before functions are even explained which makes it slightly confusing. The following lesson introduces functions, so you would probably be better off reading through the functions lesson before doing this lab.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @mbalsamo2.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
